apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nicolaslazzos/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          # if we make a change in a js file inside /src, skaffold is going to update the running pod automatically
          # but if we make a change in outside /src, skaffold is going to rebuild de docker image and update the deployment
          - src: "src/**/*.js"
            dest: .
    - image: nicolaslazzos/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nicolaslazzos/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nicolaslazzos/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nicolaslazzos/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nicolaslazzos/event-bus
      context: event-bus
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
