# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    # find all the pods with the label "posts"
    matchLabels:
      app: posts
  template:
    # configuration for every single pod
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: nicolaslazzos/posts
          imagePullPolicy: Never
---

# NodePort service

apiVersion: v1
kind: Service
metadata:
  name: posts-serv
spec:
  type: NodePort
  selector:
    # what pods should the service expose
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
---

# Cluster IP service

apiVersion: v1
kind: Service
metadata:
  name: posts-cluster-serv
spec:
  # if we dont specify the type, it will create by default a Cluster IP service
  selector:
    # what pods should the service expose
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
